import 'package:krishna_gaushala/app/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.username: "Username",
  AppStrings.enterUsername: "Enter username",
  AppStrings.pleaseEnterUsername: "Please enter username.",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password.",
  AppStrings.krishnaGaushala: "Krishna Gaushala",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.asADonationGiftService: "❖ As a donation, gift, service ❖",
  AppStrings.receipt: "Receipt",
  AppStrings.niran: "Niran",
  AppStrings.gauDohan: "Gau Dohan",
  AppStrings.vahanVyavastha: "Vahan Vyavastha",
  AppStrings.sarvar: "Sarvar",
  AppStrings.makanBandhkam: "Makan Bandhkam",
  AppStrings.bandParty: "Band Party",
  AppStrings.enterAmount: "Enter amount",
  AppStrings.pleaseEnterAmount: "Please enter amount.",
  AppStrings.amountIsNumericOnly: "Amount is numeric only.",
  AppStrings.personName: "Person Name",
  AppStrings.enterPersonName: "Enter person name",
  AppStrings.pleaseEnterPersonName: "Please enter person name.",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number.",
  AppStrings.address: "Address",
  AppStrings.enterYourAddress: "Enter your address",
  AppStrings.pleaseEnterAddress: "Please enter address.",
  AppStrings.purposeOfFund: "Purpose of fund",
  AppStrings.nisahayBinvarsiGayBaladShaySarvarFund: "Destitute Non-Hereditary Cow Bull Aid Treatment Fund",
  AppStrings.makanBandhkamFund: "Destitute Non-Hereditary Cow Bull Aid Treatment Fund",
  AppStrings.generalFund: "General Fund",
  AppStrings.cashType: "Cash Type",
  AppStrings.cash: "Cash",
  AppStrings.cheque: "Cheque",
  AppStrings.panNumber: "PAN Number",
  AppStrings.enterPanNumber: "Enter pan number",
  AppStrings.pleaseEnterPanNumber: "Please enter pan number.",
  AppStrings.chequeNumber: "Cheque Number",
  AppStrings.enterChequeNumber: "Enter cheque number",
  AppStrings.pleaseEnterChequeNumber: "Please enter cheque number.",
  AppStrings.chequeDate: "Cheque Date",
  AppStrings.enterChequeDate: "Enter cheque date",
  AppStrings.pleaseEnterChequeDate: "Please enter cheque date.",
  AppStrings.bank: "Bank",
  AppStrings.enterBank: "Enter bank",
  AppStrings.pleaseEnterBank: "Please enter bank.",
  AppStrings.branch: "Branch",
  AppStrings.enterBranch: "Enter branch",
  AppStrings.pleaseEnterBranch: "Please enter branch.",
  AppStrings.accountNumber: "Account Number",
  AppStrings.enterAccountNumber: "Enter account number",
  AppStrings.pleaseEnterAccountNumber: "Please enter account number.",
  AppStrings.chequeDetails: "Cheque Details",
  AppStrings.pleaseSelectPurposeOfFund: "Please select purpose of fund.",
  AppStrings.quantity: "Quantity",
  AppStrings.enterQuantity: "Enter quantity",
  AppStrings.pleaseEnterQuantity: "Please enter quantity.",
  AppStrings.settings: "Settings",
  AppStrings.costDetails: "Cost Details",
  AppStrings.generatedReceipts: "Generated Receipts",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "Gujarati",
  AppStrings.logOut: "Log out",
  AppStrings.searchByTitle: "Search by title",
  AppStrings.addCostDetails: "Add Cost Details",
  AppStrings.editCostDetails: "Edit Cost Details",
  AppStrings.titleOfExpenditure: "Title of Expenditure",
  AppStrings.note: "Note",
  AppStrings.pleaseEnterTitle: "Please enter title.",
  AppStrings.pleaseEnterNote: "Please enter note.",
  AppStrings.save: "Save",
  AppStrings.edit: "Edit",
  AppStrings.cancel: "Cancel",
  AppStrings.editGeneratedReceipt: "Edit Generated Receipt",
  AppStrings.delete: "Delete",
  AppStrings.view: "View",
  AppStrings.share: "Share",
  AppStrings.noDataAvailable: "No data available",
  AppStrings.areYouSureYouWantToDeleteThisCostDetails: "Are you sure, you want to delete this cost details?",
  AppStrings.areYouSureYouWantToDeleteThisReceipt: "Are you sure, you want to delete this receipt?",
  AppStrings.expenseList: "Expense List",
  AppStrings.medicine: "Medicine",
  AppStrings.khor: "Khor",
  AppStrings.majuri: "Majuri",
  AppStrings.driverSalary: "Driver Salary",
  AppStrings.buildingMaterials: "Building Materials",
  AppStrings.gowalPagar: "Gowal Pagar",
  AppStrings.diesel: "Diesel",
  AppStrings.other: "Other",
  AppStrings.selectExpenseType: "Select expense type",
  AppStrings.pleaseSelectExpenseType: "Please select expense type.",
  AppStrings.voucherDate: "Voucher date",
  AppStrings.enterVoucherDate: "Enter voucher date",
  AppStrings.pleaseEnterVoucherDate: "Please enter voucher date.",
  AppStrings.expenseType: "Expense type",
  AppStrings.enterExpenseType: "Enter expense type",
  AppStrings.pleaseEnterExpenseType: "Please enter expense type.",
};
