import 'package:krishna_gaushala/app/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.username: "Username",
  AppStrings.enterUsername: "Enter username",
  AppStrings.pleaseEnterUsername: "Please enter username.",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password.",
  AppStrings.krishnaGaushala: "Krishna Gaushala",
  AppStrings.receipt: "Receipt",
  AppStrings.niran: "Niran",
  AppStrings.gauDohan: "Gau Dohan",
  AppStrings.vahanVyavastha: "Vahan Vyavastha",
  AppStrings.sarvar: "Sarvar",
  AppStrings.makanBandhkam: "Makan Bandhkam",
  AppStrings.bandParty: "Band Party",
  AppStrings.enterAmount: "Enter amount",
  AppStrings.pleaseEnterAmount: "Please enter amount.",
  AppStrings.amountIsNumericOnly: "Amount is numeric only.",
  AppStrings.personName: "Person Name",
  AppStrings.enterPersonName: "Enter person name",
  AppStrings.pleaseEnterPersonName: "Please enter person name.",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number.",
  AppStrings.address: "Address",
  AppStrings.enterYourAddress: "Enter your address",
  AppStrings.pleaseEnterAddress: "Please enter address.",
  AppStrings.purposeOfFund: "Purpose of fund",
  AppStrings.nisahayBinvarsiGayBaladShaySarvarFund: "Destitute Non-Hereditary Cow Bull Aid Treatment Fund",
  AppStrings.makanBandhkamFund: "Destitute Non-Hereditary Cow Bull Aid Treatment Fund",
  AppStrings.generalFund: "General Fund",
  AppStrings.cashType: "Cash Type",
  AppStrings.cash: "Cash",
  AppStrings.cheque: "Cheque",
  AppStrings.panNumber: "PAN Number",
  AppStrings.enterPanNumber: "Enter pan number",
  AppStrings.pleaseEnterPanNumber: "Please enter pan number.",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "Gujarati",
  AppStrings.asADonationGiftService: "❖ As a donation, gift, service ❖",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
};
