import 'package:krishna_gaushala/app/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.username: "વપરાશકર્તા નામ",
  AppStrings.enterUsername: "વપરાશકર્તા નામ દાખલ કરો",
  AppStrings.pleaseEnterUsername: "કૃપા કરીને વપરાશકર્તા નામ દાખલ કરો.",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો.",
  AppStrings.krishnaGaushala: "ક્રિષ્ના ગૌશાળા",
  AppStrings.receipt: "રસીદ",
  AppStrings.niran: "નીરણ",
  AppStrings.gauDohan: "ગૌ દોહણ",
  AppStrings.vahanVyavastha: "વાહન વ્યવસ્થા",
  AppStrings.sarvar: "સારવાર",
  AppStrings.makanBandhkam: "મકાન બાંધકામ",
  AppStrings.bandParty: "બેન્ડ પાર્ટી",
  AppStrings.enterAmount: "રકમ દાખલ કરો",
  AppStrings.pleaseEnterAmount: "કૃપા કરીને રકમ દાખલ કરો.",
  AppStrings.amountIsNumericOnly: "રકમ માત્ર આંકડાકીય છે.",
  AppStrings.personName: "વ્યક્તિનું નામ",
  AppStrings.enterPersonName: "વ્યક્તિનું નામ દાખલ કરો",
  AppStrings.pleaseEnterPersonName: "કૃપા કરીને વ્યક્તિનું નામ દાખલ કરો.",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  AppStrings.address: "સરનામું",
  AppStrings.enterYourAddress: "તમારું સરનામું દાખલ કરો",
  AppStrings.pleaseEnterAddress: "કૃપા કરીને સરનામું દાખલ કરો.",
  AppStrings.purposeOfFund: "ભંડોળનો હેતુ",
  AppStrings.nisahayBinvarsiGayBaladShaySarvarFund: "નિઃસહાય બિનવારસી ગાય બળદ સહાય સારવાર ભંડોળ",
  AppStrings.makanBandhkamFund: "મકાન બાંધકામ ભંડોળ",
  AppStrings.generalFund: "જનરલ ભંડોળ",
  AppStrings.cashType: "રોકડ પ્રકાર",
  AppStrings.cash: "રોકડાં",
  AppStrings.cheque: "ચેક",
  AppStrings.panNumber: "PAN નંબર",
  AppStrings.enterPanNumber: "PAN નંબર દાખલ કરો",
  AppStrings.pleaseEnterPanNumber: "કૃપા કરીને PAN નંબર દાખલ કરો.",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "અંગ્રેજી",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.asADonationGiftService: "❖ દાન, ભેટ, સેવા રૂપે ❖",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
};
