import 'package:krishna_gaushala/app/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.username: "વપરાશકર્તા નામ",
  AppStrings.enterUsername: "વપરાશકર્તા નામ દાખલ કરો",
  AppStrings.pleaseEnterUsername: "કૃપા કરીને વપરાશકર્તા નામ દાખલ કરો.",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો.",
  AppStrings.krishnaGaushala: "ક્રિષ્ના ગૌશાળા",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.asADonationGiftService: "❖ દાન, ભેટ, સેવા રૂપે ❖",
  AppStrings.receipt: "રસીદ",
  AppStrings.niran: "નીરણ",
  AppStrings.gauDohan: "ગૌ દોહણ",
  AppStrings.vahanVyavastha: "વાહન વ્યવસ્થા",
  AppStrings.sarvar: "સારવાર",
  AppStrings.makanBandhkam: "મકાન બાંધકામ",
  AppStrings.bandParty: "બેન્ડ પાર્ટી",
  AppStrings.enterAmount: "રકમ દાખલ કરો",
  AppStrings.pleaseEnterAmount: "કૃપા કરીને રકમ દાખલ કરો.",
  AppStrings.amountIsNumericOnly: "રકમ માત્ર આંકડાકીય છે.",
  AppStrings.personName: "વ્યક્તિનું નામ",
  AppStrings.enterPersonName: "વ્યક્તિનું નામ દાખલ કરો",
  AppStrings.pleaseEnterPersonName: "કૃપા કરીને વ્યક્તિનું નામ દાખલ કરો.",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  AppStrings.address: "સરનામું",
  AppStrings.enterYourAddress: "તમારું સરનામું દાખલ કરો",
  AppStrings.pleaseEnterAddress: "કૃપા કરીને સરનામું દાખલ કરો.",
  AppStrings.purposeOfFund: "ભંડોળનો હેતુ",
  AppStrings.nisahayBinvarsiGayBaladShaySarvarFund: "નિઃસહાય બિનવારસી ગાય બળદ સહાય સારવાર ભંડોળ",
  AppStrings.makanBandhkamFund: "મકાન બાંધકામ ભંડોળ",
  AppStrings.generalFund: "જનરલ ભંડોળ",
  AppStrings.cashType: "રોકડ પ્રકાર",
  AppStrings.cash: "રોકડાં",
  AppStrings.cheque: "ચેક",
  AppStrings.panNumber: "PAN નંબર",
  AppStrings.enterPanNumber: "PAN નંબર દાખલ કરો",
  AppStrings.pleaseEnterPanNumber: "કૃપા કરીને PAN નંબર દાખલ કરો.",
  AppStrings.chequeNumber: "ચેક નંબર",
  AppStrings.enterChequeNumber: "ચેક નંબર દાખલ કરો",
  AppStrings.pleaseEnterChequeNumber: "કૃપા કરીને ચેક નંબર દાખલ કરો.",
  AppStrings.chequeDate: "ચેક તારીખ",
  AppStrings.enterChequeDate: "ચેક તારીખ દાખલ કરો",
  AppStrings.pleaseEnterChequeDate: "કૃપા કરીને ચેક તારીખ દાખલ કરો.",
  AppStrings.bank: "બેંક",
  AppStrings.enterBank: "બેંક દાખલ કરો",
  AppStrings.pleaseEnterBank: "કૃપા કરીને બેંક દાખલ કરો.",
  AppStrings.branch: "શાખા",
  AppStrings.enterBranch: "શાખા દાખલ કરો",
  AppStrings.pleaseEnterBranch: "કૃપા કરીને શાખા દાખલ કરો.",
  AppStrings.accountNumber: "ખાતા નંબર",
  AppStrings.enterAccountNumber: "ખાતા નંબર દાખલ કરો",
  AppStrings.pleaseEnterAccountNumber: "કૃપા કરીને ખાતા નંબર દાખલ કરો.",
  AppStrings.chequeDetails: "ચેકની વિગતો",
  AppStrings.pleaseSelectPurposeOfFund: "કૃપા કરીને ભંડોળનો હેતુ પસંદ કરો.",
  AppStrings.quantity: "જથ્થો",
  AppStrings.pleaseEnterQuantity: "કૃપા કરીને જથ્થો દાખલ કરો.",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.costDetails: "ખર્ચની વિગતો",
  AppStrings.generatedReceipts: "જનરેટ કરેલ રસીદો",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "અંગ્રેજી",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.searchByTitle: "શીર્ષક દ્વારા શોધો",
  AppStrings.addCostDetails: "ખર્ચ વિગતો ઉમેરો",
  AppStrings.editCostDetails: "ખર્ચ વિગતો સંપાદિત કરો",
  AppStrings.titleOfExpenditure: "ખર્ચનું શીર્ષક",
  AppStrings.note: "નોંધ",
  AppStrings.pleaseEnterTitle: "કૃપા કરીને શીર્ષક દાખલ કરો.",
  AppStrings.pleaseEnterNote: "કૃપા કરીને નોંધ દાખલ કરો.",
  AppStrings.save: "સેવ",
};
